{{- if eq .Values.cloud "google" }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  domains:
  - {{ .Values.domain }}
{{- end }}
