name: Pull Request Dispatcher

on:
  issue_comment:
    types:
      - created

jobs:
  slash_command_dispatch:
    name: Slash Command Dispatcher
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.WANDB_RELEASE_TOKEN }}
          reaction-token: ${{ secrets.WANDB_RELEASE_TOKEN }}
          commands: |
            test
            destroy
          permission: maintain
          issue-type: pull-request
          event-type-suffix: -command
